server:
  port: 8080
logging:
  level:
    root: info
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(O9wz9LSBmKET73iNEXGck93cG/QuX7uWpqLndXkuNULF42haXuCeIvhVhWAe/YjjoWL/kO0+BbUfgVWBXUkaAA1l0+r9t41XkMS2ySVKGUM1je0YQ2XnT4FOfG4bUdBZbdwJV/rDBe01OZfpWfhGF6fIm2tCcjS7/8AameMgP580qLItIYPpolzeMFX7Xq/Ky9A6GhEa7DgfikWyEC/f7jxonXtjjy+5Tu173GxpJt0=)
    username: ENC(6YORbSksM8E8i8+gEcXPcED6auYbCLhfUGZmzdvOl1iI9S0FQs4hjH75WLOlm1ClsdVNhxnjD4c5YTfipAfV8A==)
    password: ENC(UUevkyvkoBmZrfvccoT9iyYylI4CCQwwyXBQDvbCPI5swbveQRyf6qJo4aGqASC2ALihJwyGNTzHwVZPjxdRxA==)
  data:
    redis:
      url: ENC(VOEF25z+ArjJrEc1cmVGekxXQZd/klDAoIg3udQV5UKVu7y92XocAd8MJ37PRpxlxgJVmNMTRnnemB79KFRFTd+9ZPhNASmU4hjXw6TXjXYO8XRDRp8s2KfnWrWAMfKO81s0jidfgm517pMXKjVBQUV4kMDZFs68K+HUG31Ta7O3MMq4jCkpyx/He6zlYTeo6Z8FRPFjywdKE1z4QX34hw==)
      timeout: 3000ms
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"
      id-type: ASSIGN_UUID
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.kfile.mapper
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
jwt:
  tokenHeader: Authorization
  expireTime: 604800
  tokenHead: "Bearer "
dromara:
  x-file-storage: #文件存储配置
    default-platform: local-plus-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    local-plus:
      - platform: local-plus-1 # 存储平台标识
        enable-storage: true  #启用存储
        enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: "http://127.0.0.1:8030/local-plus/" # 访问域名，例如：“http://127.0.0.1:8030/local-plus/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: build/local-plus/ # 基础路径
        path-patterns: /local-plus/** # 访问路径
        storage-path: build/tmp/local-plus/ # 存储路径