spring:
  file-storage:
    default-platform: minio-1 #默认存储平台
    minio:
      - platform: minio-1
        enable-storage: true  # 启用存储
        access-key: sDRDIb2VaWKBRIn817J3
        secret-key: AJMnqvSgWXNlCGwFp5lmYS3TqE76tDQv9itW1BFG
        end-point: http://127.0.0.1:9001
        bucket-name: file
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
      location: ./tmp
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false
  artemis:
    embedded:
      data-directory:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kfile
      username: root
      password: root
server:
  port: 8080